In [1]:
import numpy 
numpy.__version__

'1.16.6'

In [2]:
import scipy
scipy.__version__

'1.2.3'

In [3]:
import pandas 
pandas.__version__

u'0.24.2'

In [4]:
import matplotlib 
matplotlib.__version__

'2.2.5'

# Машинное обучение и анализ данных
## Математика и Python
Задание 1

In [9]:
for x in [1, 2, 'adfa']:
    print type(x)

<type 'int'>
<type 'int'>
<type 'str'>


In [23]:
d = {"a": 1, 2: 3, [1, 2]: 1}

TypeError: unhashable type: 'list'

In [29]:
print " ".join([str(x ** 2 % 2) for x in range(4)])

0 1 0 1


In [32]:
for i in xrange(3):
    print i

0
1
2


In [41]:
df = pandas.DataFrame({'A': [1, 2, 3], 'B': [5, 6, 7]})

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
A    3 non-null int64
B    3 non-null int64
dtypes: int64(2)
memory usage: 120.0 bytes


In [45]:
a = numpy.array([1, 2, 3])
b = numpy.array([4, 5, 6])

In [46]:
numpy.dot(a, b)

32

In [47]:
a * b

array([ 4, 10, 18])

In [48]:
b.dot(a)

32

In [66]:
a = numpy.array([8, 10, -1, 0, 0])

In [68]:
a[:, numpy.newaxis]

array([[ 8],
       [10],
       [-1],
       [ 0],
       [ 0]])

In [59]:
a.reshape((5,1))

array([[ 8],
       [10],
       [-1],
       [ 0],
       [ 0]])

In [64]:
a = numpy.array([6, 3, -5])
b = numpy.array([-1, 0, 7])

In [65]:
scipy.spatial.distance.cdist(b, a, metric='euclidean')

AttributeError: 'module' object has no attribute 'spatial'

In [71]:
numpy.eye(3, 2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

### Линал

In [77]:
import re

In [82]:
f = open('sentences.txt')
word_list = set()
for line in f:
    words = [w for w in re.split('[^a-z]', line.lower()) if w != '']
    for w in words:
        word_list.add(w)
        
word_list

{'a',
 'according',
 'adjacent',
 'allow',
 'allows',
 'also',
 'an',
 'ancestor',
 'and',
 'animals',
 'any',
 'app',
 'apple',
 'are',
 'arguments',
 'artificial',
 'as',
 'available',
 'based',
 'basic',
 'be',
 'between',
 'binary',
 'both',
 'by',
 'bytes',
 'can',
 'cat',
 'catenates',
 'cats',
 'changes',
 'chromosomes',
 'clear',
 'closest',
 'command',
 'commands',
 'common',
 'community',
 'comparison',
 'computers',
 'concatenate',
 'concern',
 'connected',
 'contains',
 'content',
 'count',
 'create',
 'default',
 'delete',
 'deliberately',
 'developed',
 'diploid',
 'disk',
 'displays',
 'dogs',
 'domestic',
 'domesticated',
 'domestication',
 'download',
 'drive',
 'during',
 'ears',
 'editions',
 'enhancements',
 'entirely',
 'error',
 'every',
 'external',
 'factory',
 'faint',
 'features',
 'felis',
 'fifth',
 'file',
 'files',
 'firmware',
 'flow',
 'for',
 'frequency',
 'from',
 'genes',
 'genus',
 'has',
 'have',
 'hear',
 'high',
 'however',
 'human',
 'if',
 'in',

In [83]:
words_to_index = {w:i for i, w in enumerate(word_list)}
words_to_index

{'a': 232,
 'according': 98,
 'adjacent': 211,
 'allow': 248,
 'allows': 97,
 'also': 208,
 'an': 188,
 'ancestor': 215,
 'and': 177,
 'animals': 164,
 'any': 196,
 'app': 114,
 'apple': 113,
 'are': 58,
 'arguments': 210,
 'artificial': 68,
 'as': 190,
 'available': 51,
 'based': 88,
 'basic': 138,
 'be': 79,
 'between': 72,
 'binary': 199,
 'both': 91,
 'by': 90,
 'bytes': 42,
 'can': 172,
 'cat': 170,
 'catenates': 106,
 'cats': 136,
 'changes': 107,
 'chromosomes': 218,
 'clear': 239,
 'closest': 219,
 'command': 246,
 'commands': 92,
 'common': 77,
 'community': 115,
 'comparison': 230,
 'computers': 179,
 'concatenate': 78,
 'concern': 62,
 'connected': 227,
 'contains': 148,
 'content': 69,
 'count': 162,
 'create': 130,
 'default': 167,
 'delete': 125,
 'deliberately': 25,
 'developed': 5,
 'diploid': 85,
 'disk': 15,
 'displays': 0,
 'dogs': 141,
 'domestic': 8,
 'domesticated': 195,
 'domestication': 197,
 'download': 60,
 'drive': 22,
 'during': 37,
 'ears': 50,
 'editions':

In [86]:
a = numpy.empty((22, 254))